"""Tests for `--force`: take over files from an older Stagr when switching profiles."""
from __future__ import annotations

import tempfile
from pathlib import Path

from .harness import check, run_cli
from .plan_apply_tests import parse_entries

WORKFLOWS = ".github/workflows"


def write_legacy_standard_project(project_root: Path) -> None:
    """A repository onboarded by an older Stagr: standard workflows without the ownership line."""
    run_cli(["init", "--root", str(project_root), "--app-id", "7"])
    run_cli(["apply", "--root", str(project_root)])
    for workflow_file in (project_root / WORKFLOWS).glob("*.yml"):
        workflow_file.write_text(workflow_file.read_text(encoding="utf-8").split("\n", 1)[1], encoding="utf-8")
    (project_root / WORKFLOWS / "claude-fix.yml").write_text("name: own workflow\n", encoding="utf-8")
    (project_root / WORKFLOWS / "stage-deploy.yml").write_text("name: Deploy to staging\n", encoding="utf-8")


def test_profile_switch_works_with_files_from_an_older_stagr() -> None:
    with tempfile.TemporaryDirectory() as temporary_directory:
        project_root = Path(temporary_directory)
        write_legacy_standard_project(project_root)
        exit_code, stdout, _ = run_cli(["profile", "minimal", "--root", str(project_root)])
        check(exit_code == 0 and "standard -> minimal" in stdout, "profile: switching ignores who owns the workflow files")


def test_force_takes_over_files_from_an_older_stagr() -> None:
    with tempfile.TemporaryDirectory() as temporary_directory:
        project_root = Path(temporary_directory)
        write_legacy_standard_project(project_root)
        run_cli(["profile", "minimal", "--root", str(project_root)])
        exit_code, _, stderr = run_cli(["plan", "--root", str(project_root)])
        check(exit_code == 1 and "not generated by stagr" in stderr, "plan: without --force, files lacking the line are refused")
        exit_code, plan_stdout, _ = run_cli(["plan", "--force", "--root", str(project_root)])
        planned = {path: status for path, (status, _, _) in parse_entries(plan_stdout).items()}
        check(
            exit_code == 0
            and planned.get(f"{WORKFLOWS}/stage-review.yml") == "changed"
            and planned.get(f"{WORKFLOWS}/stage-security.yml") == "remove"
            and f"{WORKFLOWS}/claude-fix.yml" not in planned
            and f"{WORKFLOWS}/stage-deploy.yml" not in planned,
            "plan --force: overwrites produced files, removes the dropped stage, leaves the team's workflows out",
        )
        exit_code, _, _ = run_cli(["apply", "--force", "--root", str(project_root)])
        workflow_names = sorted(path.name for path in (project_root / WORKFLOWS).iterdir())
        review_first_line = (project_root / WORKFLOWS / "stage-review.yml").read_text(encoding="utf-8").split("\n", 1)[0]
        check(
            exit_code == 0
            and workflow_names == ["claude-fix.yml", "governance.yml", "routing.yml", "stage-deploy.yml", "stage-review.yml"]
            and review_first_line.startswith("# Generated by stagr"),
            "apply --force: regenerates with the ownership line, removes stage-security.yml, keeps the team's workflows",
        )
        _, replan_stdout, _ = run_cli(["plan", "--root", str(project_root)])
        check(
            {status for status, _, _ in parse_entries(replan_stdout).values()} == {"unchanged"},
            "plan: after apply --force, a plain plan sees everything unchanged",
        )


FORCE_TESTS = (
    test_profile_switch_works_with_files_from_an_older_stagr,
    test_force_takes_over_files_from_an_older_stagr,
)
