"""Tests for removing generated files the config no longer produces (`remove` in plan and apply)."""
from __future__ import annotations

import os
from pathlib import Path

import yaml

from .harness import CONFIG_FILE_PATH, EXPECTED_DOGFOOD_WORKFLOW_PATHS, check, dogfood_project, run_cli
from .plan_apply_tests import parse_entries

SECURITY_WORKFLOW_PATH = ".github/workflows/stage-security.yml"


def disable_the_security_stage(project_root: Path) -> None:
    config_path = project_root / CONFIG_FILE_PATH
    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    for stage in config["stages"]:
        if stage["id"] == "security":
            stage["enabled"] = False
    config_path.write_text(yaml.safe_dump(config), encoding="utf-8")


def test_generated_files_start_with_the_ownership_header() -> None:
    with dogfood_project() as project_root:
        run_cli(["apply", "--root", str(project_root)])
        first_lines = {
            (project_root / workflow_path).read_text(encoding="utf-8").split("\n", 1)[0]
            for workflow_path in EXPECTED_DOGFOOD_WORKFLOW_PATHS
        }
        check(
            len(first_lines) == 1 and next(iter(first_lines)).startswith("# Generated by stagr"),
            "apply: every generated file starts with the same 'Generated by stagr' header",
        )


def test_plan_lists_and_apply_removes_a_file_the_config_no_longer_produces() -> None:
    with dogfood_project() as project_root:
        run_cli(["apply", "--root", str(project_root)])
        disable_the_security_stage(project_root)
        _, plan_stdout, _ = run_cli(["plan", "--root", str(project_root)])
        check(
            parse_entries(plan_stdout).get(SECURITY_WORKFLOW_PATH, ("",))[0] == "remove",
            "plan: a generated file the config no longer produces is listed as remove",
        )
        check((project_root / SECURITY_WORKFLOW_PATH).exists(), "plan: the stale file is not deleted")
        exit_code, apply_stdout, _ = run_cli(["apply", "--root", str(project_root)])
        check(
            exit_code == 0
            and parse_entries(apply_stdout).get(SECURITY_WORKFLOW_PATH, ("",))[0] == "remove"
            and not (project_root / SECURITY_WORKFLOW_PATH).exists(),
            "apply: deletes the stale generated file and reports it as remove",
        )
        _, replan_stdout, _ = run_cli(["plan", "--root", str(project_root)])
        check(
            "remove" not in {status for status, _, _ in parse_entries(replan_stdout).values()},
            "plan: after apply, nothing is left to remove",
        )


def test_a_workflow_without_the_header_is_never_removed() -> None:
    with dogfood_project() as project_root:
        run_cli(["apply", "--root", str(project_root)])
        hand_written_file = project_root / ".github" / "workflows" / "claude-fix.yml"
        hand_written_file.write_text("name: hand written\n", encoding="utf-8")
        disable_the_security_stage(project_root)
        _, plan_stdout, _ = run_cli(["plan", "--root", str(project_root)])
        run_cli(["apply", "--root", str(project_root)])
        check(
            ".github/workflows/claude-fix.yml" not in parse_entries(plan_stdout)
            and hand_written_file.read_text(encoding="utf-8") == "name: hand written\n",
            "apply: a workflow without the header is neither listed nor removed",
        )


def test_a_symlinked_generated_file_is_never_removed() -> None:
    with dogfood_project() as project_root:
        run_cli(["apply", "--root", str(project_root)])
        security_file = project_root / SECURITY_WORKFLOW_PATH
        outside_file = project_root / "outside.yml"
        outside_file.write_text(security_file.read_text(encoding="utf-8"), encoding="utf-8")
        security_file.unlink()
        os.symlink(outside_file, security_file)
        disable_the_security_stage(project_root)
        run_cli(["apply", "--root", str(project_root)])
        check(
            security_file.is_symlink() and outside_file.exists(),
            "apply: a symlinked file is skipped, and its target is left intact",
        )


def test_a_workflow_stagr_did_not_generate_is_never_overwritten() -> None:
    with dogfood_project() as project_root:
        workflows_directory = project_root / ".github" / "workflows"
        workflows_directory.mkdir(parents=True)
        own_routing_file = workflows_directory / "routing.yml"
        own_routing_file.write_text("name: the team's own routing\n", encoding="utf-8")
        for command in ("plan", "apply"):
            exit_code, _, stderr = run_cli([command, "--root", str(project_root)])
            check(
                exit_code == 1 and "not generated by stagr" in stderr,
                f"{command}: a workflow at a generated path without the header is refused",
            )
        check(
            own_routing_file.read_text(encoding="utf-8") == "name: the team's own routing\n"
            and not (workflows_directory / "stage-review.yml").exists(),
            "apply: the team's file is untouched and nothing else is written",
        )


PRUNE_TESTS = (
    test_generated_files_start_with_the_ownership_header,
    test_plan_lists_and_apply_removes_a_file_the_config_no_longer_produces,
    test_a_workflow_without_the_header_is_never_removed,
    test_a_symlinked_generated_file_is_never_removed,
    test_a_workflow_stagr_did_not_generate_is_never_overwritten,
)
