"""Compare rendered artifacts with the files on disk, and write them.

``stagr plan`` uses ``classify_artifacts`` and ``find_stale_artifacts`` to say what would happen;
``stagr apply`` uses the same functions, then ``write_artifacts`` writes the files that are new or
changed and deletes the stale ones. A file is stale when it carries the platform renderer's
generated-file header but the config no longer produces it; a file without that header is never
touched. Every path is confined to the project root: a symlink or a directory at a target path is
refused rather than followed.
"""
from __future__ import annotations

import enum
import fnmatch
import hashlib
import os
import uuid
from dataclasses import dataclass
from pathlib import Path

from stagr.core.models import RenderedArtifact


class ArtifactWriteError(Exception):
    """A target path cannot safely be written (symlink, directory, or outside the root)."""


class ArtifactStatus(enum.Enum):
    NEW = "new"
    CHANGED = "changed"
    UNCHANGED = "unchanged"
    REMOVE = "remove"


@dataclass(frozen=True)
class ArtifactEntry:
    """One artifact, its size and hash, and what applying it would do to the target.

    For a ``REMOVE`` entry the artifact holds the stale file's current content.
    """

    artifact: RenderedArtifact
    status: ArtifactStatus

    @property
    def content_bytes(self) -> bytes:
        return self.artifact.content.encode("utf-8")

    @property
    def size_in_bytes(self) -> int:
        return len(self.content_bytes)

    @property
    def sha256_hex(self) -> str:
        return hashlib.sha256(self.content_bytes).hexdigest()


def classify_artifacts(
    project_root: Path,
    artifacts: tuple[RenderedArtifact, ...],
    generated_file_header: str | None = None,
) -> tuple[ArtifactEntry, ...]:
    """Return one entry per artifact; raise ``ArtifactWriteError`` if any target is unsafe.

    With ``generated_file_header``, an existing target that does not start with that line was not
    generated by Stagr, and is refused rather than overwritten.
    """
    return tuple(
        _classify_artifact(project_root, artifact, generated_file_header) for artifact in artifacts
    )


def find_stale_artifacts(
    project_root: Path,
    artifact_directory: str,
    generated_file_header: str,
    produced_paths: frozenset[str],
    claimed_name_patterns: tuple[str, ...] = (),
    claimed_first_line_prefix: str | None = None,
) -> tuple[ArtifactEntry, ...]:
    """Return a ``REMOVE`` entry for each generated file in ``artifact_directory`` not produced now.

    Only regular files directly in the directory are candidates: those whose first line is
    ``generated_file_header``, plus (for `--force`) those whose name matches
    ``claimed_name_patterns`` and whose first line starts with ``claimed_first_line_prefix``. A
    symlinked directory or file is skipped, never followed.
    """
    directory_path = project_root
    for segment in artifact_directory.split("/"):
        directory_path = directory_path / segment
        if directory_path.is_symlink():
            return ()
    if not directory_path.is_dir():
        return ()
    stale_entries = []
    for candidate_path in sorted(directory_path.iterdir()):
        relative_path = f"{artifact_directory}/{candidate_path.name}"
        if relative_path in produced_paths or candidate_path.is_symlink() or not candidate_path.is_file():
            continue
        candidate_text = candidate_path.read_text(encoding="utf-8", errors="replace")
        first_line = candidate_text.split("\n", 1)[0]
        is_claimed_legacy_file = (
            claimed_first_line_prefix is not None
            and first_line.startswith(claimed_first_line_prefix)
            and any(fnmatch.fnmatchcase(candidate_path.name, pattern) for pattern in claimed_name_patterns)
        )
        if first_line == generated_file_header or is_claimed_legacy_file:
            stale_entries.append(
                ArtifactEntry(RenderedArtifact(relative_path, candidate_text), ArtifactStatus.REMOVE)
            )
    return tuple(stale_entries)


def write_artifacts(project_root: Path, entries: tuple[ArtifactEntry, ...]) -> None:
    """Write every new or changed entry and delete every stale one; unchanged files are untouched."""
    for entry in entries:
        if entry.status is ArtifactStatus.UNCHANGED:
            continue
        target_path = project_root / entry.artifact.path
        if entry.status is ArtifactStatus.REMOVE:
            target_path.unlink()
        else:
            _write_atomically(target_path, entry.content_bytes)


def _classify_artifact(
    project_root: Path, artifact: RenderedArtifact, generated_file_header: str | None
) -> ArtifactEntry:
    target_path = project_root / artifact.path
    _assert_target_is_safe(project_root, artifact.path)
    if not target_path.exists():
        return ArtifactEntry(artifact, ArtifactStatus.NEW)
    existing_bytes = target_path.read_bytes()
    # Strip a CR so a checkout with CRLF line endings (Git for Windows' default) still matches.
    existing_first_line = existing_bytes.split(b"\n", 1)[0].rstrip(b"\r").decode("utf-8", errors="replace")
    if generated_file_header is not None and existing_first_line != generated_file_header:
        raise ArtifactWriteError(
            f"refusing to overwrite {artifact.path}: it was not generated by stagr (its first line "
            "is not the 'Generated by stagr' header); rename or remove that file, then run again"
        )
    is_identical = existing_bytes == artifact.content.encode("utf-8")
    return ArtifactEntry(artifact, ArtifactStatus.UNCHANGED if is_identical else ArtifactStatus.CHANGED)


def _assert_target_is_safe(project_root: Path, relative_path: str) -> None:
    """Refuse a symlink anywhere on the path below the root, and a directory as the target."""
    current_path = project_root
    for segment in relative_path.split("/"):
        current_path = current_path / segment
        if current_path.is_symlink():
            raise ArtifactWriteError(
                f"refusing to write {relative_path}: {current_path} is a symlink"
            )
    if current_path.is_dir():
        raise ArtifactWriteError(f"refusing to write {relative_path}: it is a directory")


def _write_atomically(target_path: Path, content_bytes: bytes) -> None:
    """Write next to the target, then rename over it, so a reader never sees a half-written file.

    The temporary file is created exclusively ("xb": it refuses an existing file or symlink) and with
    the mode any ordinary new file gets, so the result is a normal repository file (no chmod here).
    """
    target_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = target_path.with_name(f".{target_path.name}.{uuid.uuid4().hex[:8]}.tmp")
    try:
        with open(temporary_path, "xb") as temporary_file:
            temporary_file.write(content_bytes)
        os.replace(temporary_path, target_path)
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise
